#!/bin/bash
#
#	/etc/rc.d/init.d/cserver
#
# Starts the cserver daemon
#
# chkconfig: 345 44 56
# description: execute batch service for HandCrowd
# processname: cserver

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/sbin/cserver.sh ] || exit 0

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/cserver ]; then
	    echo -n $"Starting HandCrowd chat daemon: "
		daemon /usr/sbin/cserver.sh
		daemon /usr/sbin/pserver.sh
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cserver
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping HandCrowd chat daemon: "
	pkill -P $(pgrep cserver.sh)
	killproc /usr/sbin/cserver.sh
	pkill -P $(pgrep pserver.sh)
	killproc /usr/sbin/pserver.sh
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/cserver
	echo
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP cserver.sh
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/cserver ]; then
	    restart
	fi
	;;
status)
	status cserver.sh
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
