#!/bin/bash
#
#	/etc/rc.d/init.d/handcrowd
#
# Starts the handcrowd daemon
#
# chkconfig: 345 44 56
# description: execute batch service for HandCrowd
# processname: handcrowd

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/sbin/handcrowd.sh ] || exit 0

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/handcrowd ]; then
	    echo -n $"Starting HandCrowd batch daemon: "
	    daemon /usr/sbin/handcrowd.sh
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/handcrowd
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping HandCrowd batch daemon: "
	killproc /usr/sbin/handcrowd.sh
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/handcrowd
	echo
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP handcrowd.sh
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/handcrowd ]; then
	    restart
	fi
	;;
status)
	status handcrowd.sh
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
